spring:
  config:
    activate:
      on-profile: dev

  data:
    mongodb:
      uri: mongodb+srv://root:1234@mycluster.iehorij.mongodb.net
      database: community

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG  # MongoDB 쿼리 로그 보기
