spring:
  config:
    activate:
      on-profile: prod

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  data:
    mongodb:
      # 기본(default) 접속 — 쓰기(INSERT/UPDATE/DELETE)는 VM2(Source)로
      uri: mongodb://admin:homeprotector2025!@10.0.51.19:27017/homeprotector?authSource=admin

    # 읽기 전용(Target) DB URI를 별도 프로퍼티로 추가
  custom:
    mongodb:
      read-uri: mongodb://admin:homeprotector2025!@10.0.50.136:27017/homeprotector?authSource=admin

  elasticsearch:
    uris: http://10.0.51.192:9200

oci:
  objectstorage:
    region: ap-chuncheon-1
    namespace: axcpinxjr6te
    bucket: home-protector-images

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    hp.home_protector.domain.community.security.JwtAuthFilter: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

jwt:
  secret: b2F1dGhzZXJ2ZXJzZWNyZXRhY2Nlc3N0b2tlbm9hdXRoc2VydmVyc2VjcmV0YWNjZXNzdG9rZW9hdXRoc2VydmVyc2VjcmV0YWNjZXNzdG9rZW5vYXV0aHNlcnZlcnNlY3JldGFjY2Vzc3Rva2Vu
