spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
      max-file-size: 10MB      # 개별 파일 최대 10MB
      max-request-size: 100MB  # 전체 요청(여러 파일 합산) 최대 100MB
  data:
    mongodb:
      uri: mongodb+srv://root:1234@mycluster.iehorij.mongodb.net
      database: community
  elasticsearch:
    uris: http://localhost:9200
oci:
  objectstorage:
    region: ap-chuncheon-1
    namespace: axcpinxjr6te
    bucket: home-protector-images

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
