spring:
  config:
    activate:
      on-profile: prod

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  data:
    mongodb:
      # 프로덕션에서는 읽기 전용 타깃(10.0.50.136)으로 연결
      #uri: mongodb://readonlyUser:readonlyPassword@10.0.50.136:27017/homeprotector?authSource=admin
      uri: mongodb://admin:homeprotector2025!@10.0.51.19:27017/homeprotector?authSource=admin
  elasticsearch:
    uris: http://10.0.51.192:9200
    connection-timeout: 3s
    socket-timeout: 3s

oci:
  objectstorage:
    region: ap-chuncheon-1
    namespace: axcpinxjr6te
    bucket: home-protector-images

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    hp.home_protector.domain.community.security.JwtAuthFilter: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

jwt:
  secret: b2F1dGhzZXJ2ZXJzZWNyZXRhY2Nlc3N0b2tlbm9hdXRoc2Vyc2Vyc2VjcmV0YWNjZXNzdG9rZW9hdXRoc2Vyc2Vyc2VjcmV0YWNjZXNzdG9rZW5vYXV0aHNlcnZlcnNlY3JldGFjY2Vzc3Rva2Vu
  expiration: 3000
